BIN=main
.PHONY:bin clean help run
run:
	go run main.go
bin:
	go build main main.go
clean:
	rm -rf main
help:
	@echo	"make run           #run"
	@echo	"make bin           #bin"
	@echo   "make clean         #清除"