#
# CVS: $Id: Makefile,v 1.1 1999/06/05 00:49:12 edwardc Exp $
#
#################################################################

all: deljunk

deljunk:
	$(CC) -o deljunk deljunk.c -I../../include

clean: /tmp
	-rm -fr *~ *.o *.BAK

# DO NOT DELETE
