/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: game.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "game.pb-c.h"
void   personal_info__init
                     (PersonalInfo         *message)
{
  static PersonalInfo init_value = PERSONAL_INFO__INIT;
  *message = init_value;
}
size_t personal_info__get_packed_size
                     (const PersonalInfo *message)
{
  assert(message->base.descriptor == &personal_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t personal_info__pack
                     (const PersonalInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &personal_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t personal_info__pack_to_buffer
                     (const PersonalInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &personal_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PersonalInfo *
       personal_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PersonalInfo *)
     protobuf_c_message_unpack (&personal_info__descriptor,
                                allocator, len, data);
}
void   personal_info__free_unpacked
                     (PersonalInfo *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &personal_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   team_info__init
                     (TeamInfo         *message)
{
  static TeamInfo init_value = TEAM_INFO__INIT;
  *message = init_value;
}
size_t team_info__get_packed_size
                     (const TeamInfo *message)
{
  assert(message->base.descriptor == &team_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t team_info__pack
                     (const TeamInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &team_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t team_info__pack_to_buffer
                     (const TeamInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &team_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TeamInfo *
       team_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TeamInfo *)
     protobuf_c_message_unpack (&team_info__descriptor,
                                allocator, len, data);
}
void   team_info__free_unpacked
                     (TeamInfo *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &team_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor personal_info__field_descriptors[5] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PersonalInfo, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "year",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PersonalInfo, year),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "weapon",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PersonalInfo, weapon),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "armor",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(PersonalInfo, n_armor),
    offsetof(PersonalInfo, armor),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "money",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(PersonalInfo, has_money),
    offsetof(PersonalInfo, money),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned personal_info__field_indices_by_name[] = {
  3,   /* field[3] = armor */
  4,   /* field[4] = money */
  0,   /* field[0] = name */
  2,   /* field[2] = weapon */
  1,   /* field[1] = year */
};
static const ProtobufCIntRange personal_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor personal_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "personal_info",
  "PersonalInfo",
  "PersonalInfo",
  "",
  sizeof(PersonalInfo),
  5,
  personal_info__field_descriptors,
  personal_info__field_indices_by_name,
  1,  personal_info__number_ranges,
  (ProtobufCMessageInit) personal_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor team_info__field_descriptors[2] =
{
  {
    "leader",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(TeamInfo, leader),
    &personal_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "aaron",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(TeamInfo, aaron),
    &personal_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned team_info__field_indices_by_name[] = {
  1,   /* field[1] = aaron */
  0,   /* field[0] = leader */
};
static const ProtobufCIntRange team_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor team_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "team_info",
  "TeamInfo",
  "TeamInfo",
  "",
  sizeof(TeamInfo),
  2,
  team_info__field_descriptors,
  team_info__field_indices_by_name,
  1,  team_info__number_ranges,
  (ProtobufCMessageInit) team_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
